### ISSUE TITLE
Chrome browser issues with objectdraw

### ISSUE THREAD

**Issue by KimBruce** [gracelang/grace-web-editor#25] opened 2016-08-10 18:32 UTC
I am getting very different behavior on different browsers, with the most problems with Chrome.

Chrome:  Cannot run any objectdraw programs, even after clearing all caches.  On http://web.cecs.pdx.edu/~grace/ide/, run the following:

```
dialect "objectdraw"

def basketball: GraphicApplication = object {
   inherits graphicApplicationSize (400 @ 400)

   filledOvalAt (160 @ 50) 
                        size (100 @ 200) on (canvas)



   // required to pop up window and start graphics
   startGraphics
}
```
gives output:
```
NoSuchMethod on line 1095 of objectdraw: no method 'document' on a noObject.
  raised at noObject.document at line 1095 of objectdraw
  called from basketball.startApplication at line 1310 of objectdraw
  called from basketball.startGraphics at line 12 of objectdraw
  called from execution environment.
1094:             theWindow:= dom.window.open("", "", "width={theWidth},height={theHeight}")
1095:             theWindow.document.title:= theTitle
1096:             theWindow.document.body.appendChild(element)
Stack frames:
  test module
    basketball = ‹undefined›
```

This looks like a real problem resulting from issues with the dom in Javascript, but the code runs perfectly under Safari and Firefox at that location.
I've tried clearing every available cache, but that doesn't seem to help.

**Comment by petercowal** [comment] 2016-08-10 18:41
The problem is that an update to Chrome seems to have added stricter pop-up blocking; attempting to open a window via code fails and returns a `noObject` instead.  Allowing pop-ups fixes the problem; I'm thinking that objectdraw could print a message to the console whenever it fails to open a window for this reason.

**Comment by KimBruce** [comment] 2016-08-10 19:03
Thank you!! That solves the problem.  A better error message would definitely help.  I’ll try to add it to objectdraw.  (We’ve had that problem with firefox as well, but it gives us a better error message.)

Kim

**Comment by petercowal** [comment] 2016-08-10 19:39
Resolved with https://github.com/gracelang/objectdraw/commit/0ddebb6da9d86d2aa65526d78fbfaba3bf7d6f02.

**Closed by petercowal** 2016-08-10 19:39 UTC
