### ISSUE TITLE
Folder Bug: files present but invisible?

### ISSUE THREAD

**Issue by apblack** [gracelang/grace-web-editor#34] opened 2016-11-23 01:04 UTC
From my class Piazza site (Fall 2016, post @503):

So I made a folder named Dice game for HW5 and renamed it Dice Game before uploading the files into it. I couldn’t see them in the file browser and they didn’t get deleted when I deleted the folder they were in. Making a folder named Dice game again still didn’t make them visible, but deleting that did get rid of them, so you don’t need to use developer tools to do that. It wasn’t just case changes; 1337 haxxor 5tuff to Dice Game did the same. And making a folder with that cringe-worthy name again and renaming it to repeat the process still did not make them visible, so that’s not a workaround. Only by deleting 1337 haxxor 5tuff can you truly excise your computer of the files to upload again. Scary 5tuff.

**Comment by KimBruce** [comment] 2016-11-23 01:32
My students have seen similar problems.  I don’t use folders so can’t specify more details myself, but renaming seems problematic in general.

**Comment by Dmitri-2** [comment] 2016-11-23 08:50
I took a quick look at this, and the steps to reproduce it seem to be 1. Rename a (recently created) folder, 2. Upload a file to the folder, 3. File uploaded disappears. I'm reasonably sure that this is an isolated problem, so uploading files to the main directory, and not into a folder should be the best/safest alternative. (Also, just a note, but running the editor in Safari seems to break the folders completely.) I'll make sure to get to this and all of the other issues as soon as I can, likely in about two weeks...

**Comment by apblack** [comment] 2016-11-23 19:33
In a way, it was better when _nothing_ worked in Safari, because then the students wouldn't use it!  Now most things work, but not all.  It's usually a matter of some JavaScript feature not working — if we can find out which one, we can either Polyfill it or not use it.

I continue to tell students to use Chrome or Firefox, but we know how much attention students pay to what professor say ...

**Comment by apblack** [comment] 2016-12-09 03:12
This was _not_ fixed by commit e2d1a1b2c.  Not that those changes were intended to fix this bug, but it seems to be related: the html file tree and the `localStorage[file:...]` attributes get out of step.

**Comment by Dmitri-2** [comment] 2016-12-13 01:23
Fixed by commit: a1e328a. Issue was caused by an error in tracking the renamed directory by its new name.

**Closed by Dmitri-2** 2016-12-13 01:23 UTC
