### ISSUE TITLE
Naming with period "."

### ISSUE THREAD

**Issue by PineXmas** [gracelang/grace-web-editor#29] opened 2016-09-30 18:23 UTC
If you create a new file and name it with names including "period", like "abc." or "abc.edf", then that file is not accessible anymore for editing and removing.
Please took a look at this. I know this is not a very big issue but it may be annoyed if someone accidentally uses period in the name.
(Actually, there's a work-around to remove these files by dragging them into a folder and removing the whole folder)

**Comment by KimBruce** [comment] 2016-09-30 20:17
This is annoying and I have fallen into (and needs to be fixed).  However, all the files in that list will go away if you clear the cache (so be sure to save anything you need before doing this.

**Comment by Dmitri-2** [comment] 2016-10-01 02:30
Thanks for reporting this issue. I will try to have it fixed sometime this weekend. In the meantime, either the folder workaround, or clearing the cache works. However, as Professor Bruce noted, save all of your work first, and be careful, since this method will delete all files in the website file-system.

**Comment by Dmitri-2** [comment] 2016-10-02 21:07
Update: It looks like this is an issue with how the editor opens different types of files. When there is a period in the filename, it expects an extension that would tell it whether the file is an image, audio, or text file, so it can respond accordingly. Hence, a fix for this issue might take longer, given that it is a algorithmic problem, rather than a simple bug.

**Comment by KimBruce** [comment] 2016-10-03 00:27
Does this mean that you can load image, audio, or text files and use them in the program.  If so, I'd love to see sample code, as I'd like to use each of these.

**Comment by apblack** [comment] 2016-10-03 00:41
Is there a list of extensions that the IDE understands?  If so, the right fix might be to find the extension present after the . , and if it isn't on the list of expected extensions, to disallow the file creation with an appropriate message (Sorry, I don' know how to create a .pdf file).

Right now, the absence of an extension creates a .grace file; this seems fine.

**Comment by Dmitri-2** [comment] 2016-10-03 01:07
When the IDE was originally designed, it seems that it was intended to recognize and be able to display, images, audio, and code/text. At the moment, from my testing, it appears that the upload process for images and audio is inconsistent, and the display functionality for image files is broken at the moment. To test these features, simply create a new file in the IDE with a .jpg or .mp3 extension, then open it. It will be empty, but the IDE will attempt to display/play the .mp3 or .jpg file. 

The list of currently supported file types is: 
**Text Files:** ".grace" ".txt" ".json" ".xml"  ".js" ".html"  ".xhtml"
**Image Files:** ".jpg" ".jpeg"  ".bmp" ".gif" ".png"
**Audio Files:**  ".mp3" ".ogg" ".wav"

I will take Professor Black's approach, and disallow the creation/upload of files with improper extensions or formats. Additionally, I will work on fixing the display and upload process for images and audio.

**Comment by KimBruce** [comment] 2016-10-03 02:45
If I upload a txt file into the browser, is there a way that I can access it from a program as a file?

**Comment by Dmitri-2** [comment] 2016-12-24 08:52
Filenames with unknown or unsupported extensions are now blocked with commit 4041d6b. This solves the main issue being discussed here. However, there are still some other problems to solve:
- The display functionality for audio and image files is broken, and needs to be fixed
- Feature request: be able to access files in the IDE file system from within Grace programs

It would probably be best to open new issue trackers for these two separate problems.

**Closed by Dmitri-2** 2016-12-24 08:52 UTC
Labels: this week!
